"""empty message

Revision ID: 02db975ec0d9
Revises: 
Create Date: 2020-08-27 02:37:15.898165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02db975ec0d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overall_rating', sa.String(), nullable=False),
    sa.Column('classes', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rate_my_professor_id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('professor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('professor')
    # ### end Alembic commands ###
